/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Painel;

import javax.swing.JFrame;

/**
 *
 * @author Aluno
 */
public class Inicial extends javax.swing.JFrame {

    /**
     * Creates new form Inicial
     */
    public Inicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jButton1 = new javax.swing.JButton();
        jMenu1 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        btnBMfundoBranco = new javax.swing.JPanel();
        btnBotaoSacola = new javax.swing.JButton();
        btnBMfundoAzul = new javax.swing.JMenuBar();
        btnMenu = new javax.swing.JMenu();
        btnBotaoMenu1 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        btnBotaoMenu2 = new javax.swing.JMenu();
        btnBotaoMenu3 = new javax.swing.JMenu();
        btnBotaoMenu4 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jButton1.setText("jButton1");

        jMenu1.setText("jMenu1");

        jMenu7.setText("File");
        jMenuBar1.add(jMenu7);

        jMenu10.setText("Edit");
        jMenuBar1.add(jMenu10);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBMfundoBranco.setBackground(new java.awt.Color(255, 255, 255));
        btnBMfundoBranco.setPreferredSize(new java.awt.Dimension(341, 550));

        btnBotaoSacola.setBackground(new java.awt.Color(102, 204, 255));
        btnBotaoSacola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loja/roupas/resources/renewable_9172793 (1).png"))); // NOI18N
        btnBotaoSacola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBotaoSacolaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnBMfundoBrancoLayout = new javax.swing.GroupLayout(btnBMfundoBranco);
        btnBMfundoBranco.setLayout(btnBMfundoBrancoLayout);
        btnBMfundoBrancoLayout.setHorizontalGroup(
            btnBMfundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBMfundoBrancoLayout.createSequentialGroup()
                .addGap(0, 293, Short.MAX_VALUE)
                .addComponent(btnBotaoSacola, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnBMfundoBrancoLayout.setVerticalGroup(
            btnBMfundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBMfundoBrancoLayout.createSequentialGroup()
                .addContainerGap(429, Short.MAX_VALUE)
                .addComponent(btnBotaoSacola)
                .addGap(223, 223, 223))
        );

        btnBMfundoAzul.setBackground(new java.awt.Color(102, 204, 255));
        btnBMfundoAzul.setForeground(new java.awt.Color(0, 255, 255));
        btnBMfundoAzul.setOpaque(true);

        btnMenu.setBackground(new java.awt.Color(102, 204, 255));
        btnMenu.setForeground(new java.awt.Color(153, 153, 153));
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loja/roupas/resources/menu_1828551 (1).png"))); // NOI18N
        btnMenu.setOpaque(true);

        btnBotaoMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loja/roupas/resources/user_3293334.png"))); // NOI18N
        btnBotaoMenu1.setText("Login");

        jMenu9.setText("Usuario");
        btnBotaoMenu1.add(jMenu9);

        jMenu11.setText("Fornecedor");
        btnBotaoMenu1.add(jMenu11);

        btnMenu.add(btnBotaoMenu1);

        btnBotaoMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loja/roupas/resources/label_6807774.png"))); // NOI18N
        btnBotaoMenu2.setText("Categorias");
        btnMenu.add(btnBotaoMenu2);

        btnBotaoMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loja/roupas/resources/heart_7082951 (1).png"))); // NOI18N
        btnBotaoMenu3.setText("Meus favoritos");
        btnMenu.add(btnBotaoMenu3);

        btnBotaoMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loja/roupas/resources/product_6806351.png"))); // NOI18N
        btnBotaoMenu4.setText("Meus pedidos");
        btnMenu.add(btnBotaoMenu4);

        btnBMfundoAzul.add(btnMenu);

        jMenu2.setText("               ");
        btnBMfundoAzul.add(jMenu2);

        jMenu3.setText("          ");
        btnBMfundoAzul.add(jMenu3);

        jMenu6.setText("         ");
        btnBMfundoAzul.add(jMenu6);

        jMenu8.setText("                                       ");
        btnBMfundoAzul.add(jMenu8);

        setJMenuBar(btnBMfundoAzul);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBMfundoBranco, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBMfundoBranco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBotaoSacolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBotaoSacolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBotaoSacolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar btnBMfundoAzul;
    private javax.swing.JPanel btnBMfundoBranco;
    private javax.swing.JMenu btnBotaoMenu1;
    private javax.swing.JMenu btnBotaoMenu2;
    private javax.swing.JMenu btnBotaoMenu3;
    private javax.swing.JMenu btnBotaoMenu4;
    private javax.swing.JButton btnBotaoSacola;
    private javax.swing.JMenu btnMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    // End of variables declaration//GEN-END:variables
}
